name: remote dispatch
on: [push]
jobs:
  trigger-repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository-dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{secrets.GH_PAT}}
          repository: aliksai-bh/uptime-monitoring
          event-type: triggering-event
          client-payload: '{"website":"samsung", "url":"https://samsung.com"}'